version: '3.8'

services:
  app:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: uuu7892/product_management:latest
    container_name: container_web_pm
    ports:
      - "8000:3000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - pm-networks
      
networks:
  pm-networks:
    driver: bridge