name: CI/CD push image to server docker hub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # step ci 
  step_ci:
    runs-on: ubuntu-latest
    steps:
      # pull source code to machine linux ubuntu runner
      - name: Checkout code
        uses: actions/checkout@v4

      # login to docker hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      # build image docker
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/product_management:latest
    
  # step_cd:
  step_cd:
    needs: step_ci
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server via ssh
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # send with path folder
            cd ~/Vscode/Study/Ops/Product-management

            # pull image docker lastest
            docker compose pull

            # run docker compose
            docker compose up -d

            # remove image docker dangling
            docker image prune -f
